---
- name: Check SSH service status
  hosts: all
  become: true
  tasks:
    - name: Get SSH status
      systemd:
        name: sshd
        state: status
      register: ssh_status

    - name: Display SSH status
      debug:
        var: ssh_status
