---
- name: Check SSH service status
  hosts: all
  become: true
  tasks:
    - name: Get SSH status
      shell: systemctl status sshd
      register: ssh_status

    - name: Display SSH status
      debug:
        var: ssh_status.stdout
