---
- name: Check SSH service status
  hosts: all
  become: true
  tasks:
    - name: Get SSH status
      shell: systemctl status sshd
      register: ssh_status

    - name: Display SSH status
      debug:
        var: ssh_status.stdout

    - name: Get CS status
      shell: systemctl status falcon-sensor
      register: cs_status

    - name: Display CS status
      debug:
        var: cs_status.stdout
        
    - name: Get Rapid status
      shell: systemctl status ir_agent
      register: rapid_status

    - name: Display Rapid status
      debug:
        var: rapid_status.stdout
